
//! THIS FILE IS GENERATED NOT CHANGE
// prettier-ignore
export const routes = [
  {
    filename: "0-main.md",
    import: () => import("../content/0-main.md"),
    metadata: {"publish":true,"filename":"0-main.md","sortKey":["900000000","main.md"],"slug":"main","title":"หนังสือธรรมะ ธรรมชาติ","titlePrev":"ธรรมะ ธรรมชาติ\nโดย อาจารย์น้องไนซ์ นิรมิต เทวาจุติ","tags":["หนังสือ"]},
    paginate: {"next":{"publish":true,"filename":"1-preface.md","sortKey":["900000001","preface.md"],"slug":"preface","title":"คำนำ"}},
  },
  {
    filename: "1-preface.md",
    import: () => import("../content/1-preface.md"),
    metadata: {"publish":true,"filename":"1-preface.md","sortKey":["900000001","preface.md"],"slug":"preface","title":"คำนำ"},
    paginate: {"prev":{"publish":true,"filename":"0-main.md","sortKey":["900000000","main.md"],"slug":"main","title":"หนังสือธรรมะ ธรรมชาติ","titlePrev":"ธรรมะ ธรรมชาติ\nโดย อาจารย์น้องไนซ์ นิรมิต เทวาจุติ","tags":["หนังสือ"]},"next":{"publish":true,"filename":"2-biography.md","sortKey":["900000002","biography.md"],"slug":"biography","title":"ประวัติความเป็นมา","titlePrev":"ประวัติความเป็นมา \"องค์เพชรภัทรนาคานาคราช\""}},
  },
  {
    filename: "2-biography.md",
    import: () => import("../content/2-biography.md"),
    metadata: {"publish":true,"filename":"2-biography.md","sortKey":["900000002","biography.md"],"slug":"biography","title":"ประวัติความเป็นมา","titlePrev":"ประวัติความเป็นมา \"องค์เพชรภัทรนาคานาคราช\""},
    paginate: {"prev":{"publish":true,"filename":"1-preface.md","sortKey":["900000001","preface.md"],"slug":"preface","title":"คำนำ"},"next":{"publish":true,"filename":"3-learning-within-mind.md","sortKey":["900000003","learning","within","mind.md"],"slug":"learning-within-mind","title":"ทำไมต้องใช้จิตเรียน","titlePrev":"การเรียนรู้ด้วยจิต","tags":["ข้อธรรม"]}},
  },
  {
    filename: "3-learning-within-mind.md",
    import: () => import("../content/3-learning-within-mind.md"),
    metadata: {"publish":true,"filename":"3-learning-within-mind.md","sortKey":["900000003","learning","within","mind.md"],"slug":"learning-within-mind","title":"ทำไมต้องใช้จิตเรียน","titlePrev":"การเรียนรู้ด้วยจิต","tags":["ข้อธรรม"]},
    paginate: {"prev":{"publish":true,"filename":"2-biography.md","sortKey":["900000002","biography.md"],"slug":"biography","title":"ประวัติความเป็นมา","titlePrev":"ประวัติความเป็นมา \"องค์เพชรภัทรนาคานาคราช\""},"next":{"publish":true,"filename":"4-angulimaal.md","sortKey":["900000004","angulimaal.md"],"slug":"angulimaal-karma","title":"กรรมขององคุลีมาล","titlePrev":"ข้อธรรมอันเกี่ยวกับองคุลีมาล","tags":["ข้อธรรม"]}},
  },
  {
    filename: "4-angulimaal.md",
    import: () => import("../content/4-angulimaal.md"),
    metadata: {"publish":true,"filename":"4-angulimaal.md","sortKey":["900000004","angulimaal.md"],"slug":"angulimaal-karma","title":"กรรมขององคุลีมาล","titlePrev":"ข้อธรรมอันเกี่ยวกับองคุลีมาล","tags":["ข้อธรรม"]},
    paginate: {"prev":{"publish":true,"filename":"3-learning-within-mind.md","sortKey":["900000003","learning","within","mind.md"],"slug":"learning-within-mind","title":"ทำไมต้องใช้จิตเรียน","titlePrev":"การเรียนรู้ด้วยจิต","tags":["ข้อธรรม"]},"next":{"publish":true,"filename":"5-vimut-by-smart.md","sortKey":["900000005","vimut","by","smart.md"],"slug":"vimut-by-smarti","title":"หลุดพ้นด้วยฌาน","titlePrev":"วิมุตติ คือ การหลุดพ้น","tags":["ข้อธรรม"]}},
  },
  {
    filename: "5-vimut-by-smart.md",
    import: () => import("../content/5-vimut-by-smart.md"),
    metadata: {"publish":true,"filename":"5-vimut-by-smart.md","sortKey":["900000005","vimut","by","smart.md"],"slug":"vimut-by-smarti","title":"หลุดพ้นด้วยฌาน","titlePrev":"วิมุตติ คือ การหลุดพ้น","tags":["ข้อธรรม"]},
    paginate: {"prev":{"publish":true,"filename":"4-angulimaal.md","sortKey":["900000004","angulimaal.md"],"slug":"angulimaal-karma","title":"กรรมขององคุลีมาล","titlePrev":"ข้อธรรมอันเกี่ยวกับองคุลีมาล","tags":["ข้อธรรม"]},"next":{"publish":true,"filename":"6-nirvana-and-karm.md","sortKey":["900000006","nirvana","and","karm.md"],"slug":"nirvana-and-karma","title":"ยิ่งใกล้นิพพาน ยิ่งเร่งกรรม","titlePrev":"อธิษฐานเอาพระนิพพาน","tags":["ข้อธรรม"]}},
  },
  {
    filename: "6-nirvana-and-karm.md",
    import: () => import("../content/6-nirvana-and-karm.md"),
    metadata: {"publish":true,"filename":"6-nirvana-and-karm.md","sortKey":["900000006","nirvana","and","karm.md"],"slug":"nirvana-and-karma","title":"ยิ่งใกล้นิพพาน ยิ่งเร่งกรรม","titlePrev":"อธิษฐานเอาพระนิพพาน","tags":["ข้อธรรม"]},
    paginate: {"prev":{"publish":true,"filename":"5-vimut-by-smart.md","sortKey":["900000005","vimut","by","smart.md"],"slug":"vimut-by-smarti","title":"หลุดพ้นด้วยฌาน","titlePrev":"วิมุตติ คือ การหลุดพ้น","tags":["ข้อธรรม"]},"next":{"publish":true,"filename":"7-bless.md","sortKey":["900000007","bless.md"],"slug":"bless","title":"ขอพร","titlePrev":"การพิจารณา พรวันเกิด","tags":["ข้อธรรม"]}},
  },
  {
    filename: "7-bless.md",
    import: () => import("../content/7-bless.md"),
    metadata: {"publish":true,"filename":"7-bless.md","sortKey":["900000007","bless.md"],"slug":"bless","title":"ขอพร","titlePrev":"การพิจารณา พรวันเกิด","tags":["ข้อธรรม"]},
    paginate: {"prev":{"publish":true,"filename":"6-nirvana-and-karm.md","sortKey":["900000006","nirvana","and","karm.md"],"slug":"nirvana-and-karma","title":"ยิ่งใกล้นิพพาน ยิ่งเร่งกรรม","titlePrev":"อธิษฐานเอาพระนิพพาน","tags":["ข้อธรรม"]},"next":{"publish":true,"filename":"8-teacher.md","sortKey":["900000008","teacher.md"],"slug":"teacher","title":"สายสัมพันธ์ ครูบาอาจารย์","titlePrev":"การพิจารณา สายสัมพันธ์ ครูบาอาจารย์","tags":["ข้อธรรม"]}},
  },
  {
    filename: "8-teacher.md",
    import: () => import("../content/8-teacher.md"),
    metadata: {"publish":true,"filename":"8-teacher.md","sortKey":["900000008","teacher.md"],"slug":"teacher","title":"สายสัมพันธ์ ครูบาอาจารย์","titlePrev":"การพิจารณา สายสัมพันธ์ ครูบาอาจารย์","tags":["ข้อธรรม"]},
    paginate: {"prev":{"publish":true,"filename":"7-bless.md","sortKey":["900000007","bless.md"],"slug":"bless","title":"ขอพร","titlePrev":"การพิจารณา พรวันเกิด","tags":["ข้อธรรม"]},"next":{"publish":true,"filename":"9-kill.md","sortKey":["900000009","kill.md"],"slug":"kill","title":"กรรมจากการฆ่าสัตว์ในอดีต","titlePrev":"กรรมจากอดีตในการฆ่าสัตว์","tags":["ข้อธรรม"]}},
  },
  {
    filename: "9-kill.md",
    import: () => import("../content/9-kill.md"),
    metadata: {"publish":true,"filename":"9-kill.md","sortKey":["900000009","kill.md"],"slug":"kill","title":"กรรมจากการฆ่าสัตว์ในอดีต","titlePrev":"กรรมจากอดีตในการฆ่าสัตว์","tags":["ข้อธรรม"]},
    paginate: {"prev":{"publish":true,"filename":"8-teacher.md","sortKey":["900000008","teacher.md"],"slug":"teacher","title":"สายสัมพันธ์ ครูบาอาจารย์","titlePrev":"การพิจารณา สายสัมพันธ์ ครูบาอาจารย์","tags":["ข้อธรรม"]},"next":{"publish":true,"filename":"10-overtime.md","sortKey":["900000010","overtime.md"],"slug":"overtime","title":"เวลานั้นให้สำหรับการฝึกความเพียร","titlePrev":"เวลานั้นให้สำหรับการฝึกความเพียร","tags":["ข้อธรรม"]}},
  },
  {
    filename: "10-overtime.md",
    import: () => import("../content/10-overtime.md"),
    metadata: {"publish":true,"filename":"10-overtime.md","sortKey":["900000010","overtime.md"],"slug":"overtime","title":"เวลานั้นให้สำหรับการฝึกความเพียร","titlePrev":"เวลานั้นให้สำหรับการฝึกความเพียร","tags":["ข้อธรรม"]},
    paginate: {"prev":{"publish":true,"filename":"9-kill.md","sortKey":["900000009","kill.md"],"slug":"kill","title":"กรรมจากการฆ่าสัตว์ในอดีต","titlePrev":"กรรมจากอดีตในการฆ่าสัตว์","tags":["ข้อธรรม"]},"next":{"publish":true,"filename":"11-pain-before-dea.md","sortKey":["900000011","pain","before","dea.md"],"slug":"pain-before-dead","title":"เจ็บร่างกายก่อนสิ้นชีวิต","titlePrev":"การพิจารณา วิธีการเผชิญ กับ ความเจ็บปวดในกายสังขาร ก่อนสิ้น","tags":["ข้อธรรม"]}},
  },
  {
    filename: "11-pain-before-dea.md",
    import: () => import("../content/11-pain-before-dea.md"),
    metadata: {"publish":true,"filename":"11-pain-before-dea.md","sortKey":["900000011","pain","before","dea.md"],"slug":"pain-before-dead","title":"เจ็บร่างกายก่อนสิ้นชีวิต","titlePrev":"การพิจารณา วิธีการเผชิญ กับ ความเจ็บปวดในกายสังขาร ก่อนสิ้น","tags":["ข้อธรรม"]},
    paginate: {"prev":{"publish":true,"filename":"10-overtime.md","sortKey":["900000010","overtime.md"],"slug":"overtime","title":"เวลานั้นให้สำหรับการฝึกความเพียร","titlePrev":"เวลานั้นให้สำหรับการฝึกความเพียร","tags":["ข้อธรรม"]},"next":{"publish":true,"filename":"12-light.md","sortKey":["900000012","light.md"],"slug":"light","title":"แสง สี ในสมาธิ","titlePrev":"การพิจารณา แสง สี ในสมาธิ","tags":["ข้อธรรม"]}},
  },
  {
    filename: "12-light.md",
    import: () => import("../content/12-light.md"),
    metadata: {"publish":true,"filename":"12-light.md","sortKey":["900000012","light.md"],"slug":"light","title":"แสง สี ในสมาธิ","titlePrev":"การพิจารณา แสง สี ในสมาธิ","tags":["ข้อธรรม"]},
    paginate: {"prev":{"publish":true,"filename":"11-pain-before-dea.md","sortKey":["900000011","pain","before","dea.md"],"slug":"pain-before-dead","title":"เจ็บร่างกายก่อนสิ้นชีวิต","titlePrev":"การพิจารณา วิธีการเผชิญ กับ ความเจ็บปวดในกายสังขาร ก่อนสิ้น","tags":["ข้อธรรม"]},"next":{"publish":true,"filename":"13-step-of-improve.md","sortKey":["900000013","step","of","improve.md"],"slug":"step-of-improve","title":"การพัฒนาจิตของการปฏิบัติ","titlePrev":"การพัฒนาจิตของการปฏิบัติ","tags":["ข้อธรรม"]}},
  },
  {
    filename: "13-step-of-improve.md",
    import: () => import("../content/13-step-of-improve.md"),
    metadata: {"publish":true,"filename":"13-step-of-improve.md","sortKey":["900000013","step","of","improve.md"],"slug":"step-of-improve","title":"การพัฒนาจิตของการปฏิบัติ","titlePrev":"การพัฒนาจิตของการปฏิบัติ","tags":["ข้อธรรม"]},
    paginate: {"prev":{"publish":true,"filename":"12-light.md","sortKey":["900000012","light.md"],"slug":"light","title":"แสง สี ในสมาธิ","titlePrev":"การพิจารณา แสง สี ในสมาธิ","tags":["ข้อธรรม"]},"next":{"publish":true,"filename":"14-bad-monk.md","sortKey":["900000014","bad","monk.md"],"slug":"bad-monk","title":"พระนิสัยไม่ดี","titlePrev":"เณร ถูกพระที่วัดเดียวกันคอยกลั่นแกล้ง คอยมาแขวะ","tags":["ข้อธรรม"]}},
  },
  {
    filename: "14-bad-monk.md",
    import: () => import("../content/14-bad-monk.md"),
    metadata: {"publish":true,"filename":"14-bad-monk.md","sortKey":["900000014","bad","monk.md"],"slug":"bad-monk","title":"พระนิสัยไม่ดี","titlePrev":"เณร ถูกพระที่วัดเดียวกันคอยกลั่นแกล้ง คอยมาแขวะ","tags":["ข้อธรรม"]},
    paginate: {"prev":{"publish":true,"filename":"13-step-of-improve.md","sortKey":["900000013","step","of","improve.md"],"slug":"step-of-improve","title":"การพัฒนาจิตของการปฏิบัติ","titlePrev":"การพัฒนาจิตของการปฏิบัติ","tags":["ข้อธรรม"]},"next":{"publish":true,"filename":"15-birth.md","sortKey":["900000015","birth.md"],"slug":"birth","title":"วันเดือนปีเกิด","titlePrev":"เด็กที่จะเกิดเป็นคนดีหรือไม่ดีขึ้นอยู่กับวันเดือนปีเกิดหรือไม่","tags":["ข้อธรรม"]}},
  },
  {
    filename: "15-birth.md",
    import: () => import("../content/15-birth.md"),
    metadata: {"publish":true,"filename":"15-birth.md","sortKey":["900000015","birth.md"],"slug":"birth","title":"วันเดือนปีเกิด","titlePrev":"เด็กที่จะเกิดเป็นคนดีหรือไม่ดีขึ้นอยู่กับวันเดือนปีเกิดหรือไม่","tags":["ข้อธรรม"]},
    paginate: {"prev":{"publish":true,"filename":"14-bad-monk.md","sortKey":["900000014","bad","monk.md"],"slug":"bad-monk","title":"พระนิสัยไม่ดี","titlePrev":"เณร ถูกพระที่วัดเดียวกันคอยกลั่นแกล้ง คอยมาแขวะ","tags":["ข้อธรรม"]},"next":{"publish":true,"filename":"16-nirvana.md","sortKey":["900000016","nirvana.md"],"slug":"nirvana","title":"การพิจารณา เรื่องแดนสุขาวดี","titlePrev":"การพิจารณา เรื่องแดนสุขาวดี","tags":["ข้อธรรม"]}},
  },
  {
    filename: "16-nirvana.md",
    import: () => import("../content/16-nirvana.md"),
    metadata: {"publish":true,"filename":"16-nirvana.md","sortKey":["900000016","nirvana.md"],"slug":"nirvana","title":"การพิจารณา เรื่องแดนสุขาวดี","titlePrev":"การพิจารณา เรื่องแดนสุขาวดี","tags":["ข้อธรรม"]},
    paginate: {"prev":{"publish":true,"filename":"15-birth.md","sortKey":["900000015","birth.md"],"slug":"birth","title":"วันเดือนปีเกิด","titlePrev":"เด็กที่จะเกิดเป็นคนดีหรือไม่ดีขึ้นอยู่กับวันเดือนปีเกิดหรือไม่","tags":["ข้อธรรม"]},"next":{"publish":true,"filename":"17-answer-by-own-knowledge.md","sortKey":["900000017","answer","by","own","knowledge.md"],"slug":"answer-by-own-knowledge","title":"ตอบคำถามธรรมอื่นๆตามที่ตนเข้าใจ","titlePrev":"ตอบคำถามธรรมอื่นๆตามที่ตนเข้าใจ","tags":["ข้อธรรม"]}},
  },
  {
    filename: "17-answer-by-own-knowledge.md",
    import: () => import("../content/17-answer-by-own-knowledge.md"),
    metadata: {"publish":true,"filename":"17-answer-by-own-knowledge.md","sortKey":["900000017","answer","by","own","knowledge.md"],"slug":"answer-by-own-knowledge","title":"ตอบคำถามธรรมอื่นๆตามที่ตนเข้าใจ","titlePrev":"ตอบคำถามธรรมอื่นๆตามที่ตนเข้าใจ","tags":["ข้อธรรม"]},
    paginate: {"prev":{"publish":true,"filename":"16-nirvana.md","sortKey":["900000016","nirvana.md"],"slug":"nirvana","title":"การพิจารณา เรื่องแดนสุขาวดี","titlePrev":"การพิจารณา เรื่องแดนสุขาวดี","tags":["ข้อธรรม"]},"next":{"publish":true,"filename":"18-hyperkinetic.md","sortKey":["900000018","hyperkinetic.md"],"slug":"hyperkinetic","title":"นั่งสมาธิ แต่จิตไม่นิ่ง","titlePrev":"นั่งสมาธิ แต่จิตไม่นิ่ง ควรทำอย่างไร","tags":["ข้อธรรม"],"bookPage":55}},
  },
  {
    filename: "18-hyperkinetic.md",
    import: () => import("../content/18-hyperkinetic.md"),
    metadata: {"publish":true,"filename":"18-hyperkinetic.md","sortKey":["900000018","hyperkinetic.md"],"slug":"hyperkinetic","title":"นั่งสมาธิ แต่จิตไม่นิ่ง","titlePrev":"นั่งสมาธิ แต่จิตไม่นิ่ง ควรทำอย่างไร","tags":["ข้อธรรม"],"bookPage":55},
    paginate: {"prev":{"publish":true,"filename":"17-answer-by-own-knowledge.md","sortKey":["900000017","answer","by","own","knowledge.md"],"slug":"answer-by-own-knowledge","title":"ตอบคำถามธรรมอื่นๆตามที่ตนเข้าใจ","titlePrev":"ตอบคำถามธรรมอื่นๆตามที่ตนเข้าใจ","tags":["ข้อธรรม"]},"next":{"publish":true,"filename":"19-light2.md","sortKey":["900000019","light2.md"],"slug":"light2","title":"เห็นแสงในฌาน","titlePrev":"หากสมาธิเกิดขึ้นจนจะเข้าฌาน จะเห็นแสง","tags":["ข้อธรรม"]}},
  },
  {
    filename: "19-light2.md",
    import: () => import("../content/19-light2.md"),
    metadata: {"publish":true,"filename":"19-light2.md","sortKey":["900000019","light2.md"],"slug":"light2","title":"เห็นแสงในฌาน","titlePrev":"หากสมาธิเกิดขึ้นจนจะเข้าฌาน จะเห็นแสง","tags":["ข้อธรรม"]},
    paginate: {"prev":{"publish":true,"filename":"18-hyperkinetic.md","sortKey":["900000018","hyperkinetic.md"],"slug":"hyperkinetic","title":"นั่งสมาธิ แต่จิตไม่นิ่ง","titlePrev":"นั่งสมาธิ แต่จิตไม่นิ่ง ควรทำอย่างไร","tags":["ข้อธรรม"],"bookPage":55},"next":{"publish":true,"filename":"20-everyday-life.md","sortKey":["900000020","everyday","life.md"],"slug":"everyday-life","title":"ในการใช้ชีวิตประจำวันก็บรรลุได้","titlePrev":"ในการใช้ชีวิตประจำวันก็บรรลุได้","tags":["ข้อธรรม"],"bookPage":58}},
  },
  {
    filename: "20-everyday-life.md",
    import: () => import("../content/20-everyday-life.md"),
    metadata: {"publish":true,"filename":"20-everyday-life.md","sortKey":["900000020","everyday","life.md"],"slug":"everyday-life","title":"ในการใช้ชีวิตประจำวันก็บรรลุได้","titlePrev":"ในการใช้ชีวิตประจำวันก็บรรลุได้","tags":["ข้อธรรม"],"bookPage":58},
    paginate: {"prev":{"publish":true,"filename":"19-light2.md","sortKey":["900000019","light2.md"],"slug":"light2","title":"เห็นแสงในฌาน","titlePrev":"หากสมาธิเกิดขึ้นจนจะเข้าฌาน จะเห็นแสง","tags":["ข้อธรรม"]},"next":{"publish":true,"filename":"21-begin-of-human.md","sortKey":["900000021","begin","of","human.md"],"slug":"begin-of-human","title":"มนุษย์เกิดมาจากภพภูมิใด","titlePrev":"มนุษย์เกิดมาจากภพภูมิใด","tags":["ข้อธรรม"]}},
  },
  {
    filename: "21-begin-of-human.md",
    import: () => import("../content/21-begin-of-human.md"),
    metadata: {"publish":true,"filename":"21-begin-of-human.md","sortKey":["900000021","begin","of","human.md"],"slug":"begin-of-human","title":"มนุษย์เกิดมาจากภพภูมิใด","titlePrev":"มนุษย์เกิดมาจากภพภูมิใด","tags":["ข้อธรรม"]},
    paginate: {"prev":{"publish":true,"filename":"20-everyday-life.md","sortKey":["900000020","everyday","life.md"],"slug":"everyday-life","title":"ในการใช้ชีวิตประจำวันก็บรรลุได้","titlePrev":"ในการใช้ชีวิตประจำวันก็บรรลุได้","tags":["ข้อธรรม"],"bookPage":58},"next":{"publish":true,"filename":"22-just-know.md","sortKey":["900000022","just","know.md"],"slug":"just-know","title":"การรู้เฉยๆ","titlePrev":"การพิจารณา การรู้เฉยๆ","tags":["ข้อธรรม"]}},
  },
  {
    filename: "22-just-know.md",
    import: () => import("../content/22-just-know.md"),
    metadata: {"publish":true,"filename":"22-just-know.md","sortKey":["900000022","just","know.md"],"slug":"just-know","title":"การรู้เฉยๆ","titlePrev":"การพิจารณา การรู้เฉยๆ","tags":["ข้อธรรม"]},
    paginate: {"prev":{"publish":true,"filename":"21-begin-of-human.md","sortKey":["900000021","begin","of","human.md"],"slug":"begin-of-human","title":"มนุษย์เกิดมาจากภพภูมิใด","titlePrev":"มนุษย์เกิดมาจากภพภูมิใด","tags":["ข้อธรรม"]},"next":{"publish":true,"filename":"23-suicide.md","sortKey":["900000023","suicide.md"],"slug":"suicide","title":"กรรมจากการฆ่าตัวตาย","titlePrev":"กรรมจากการฆ่าตัวตาย","tags":["ข้อธรรม"],"bookPage":63}},
  },
  {
    filename: "23-suicide.md",
    import: () => import("../content/23-suicide.md"),
    metadata: {"publish":true,"filename":"23-suicide.md","sortKey":["900000023","suicide.md"],"slug":"suicide","title":"กรรมจากการฆ่าตัวตาย","titlePrev":"กรรมจากการฆ่าตัวตาย","tags":["ข้อธรรม"],"bookPage":63},
    paginate: {"prev":{"publish":true,"filename":"22-just-know.md","sortKey":["900000022","just","know.md"],"slug":"just-know","title":"การรู้เฉยๆ","titlePrev":"การพิจารณา การรู้เฉยๆ","tags":["ข้อธรรม"]},"next":{"publish":true,"filename":"24-see-dhumma.md","sortKey":["900000024","see","dhumma.md"],"slug":"see-dhumma","title":"มองทุกสิ่งเป็นธรรมชาติ น้อมรับสิ่งที่เกิด ในสภาวะจิต","titlePrev":"มองทุกสิ่งเป็นธรรมชาติ น้อมรับสิ่งที่เกิด ในสภาวะจิต","tags":["ข้อธรรม"]}},
  },
  {
    filename: "24-see-dhumma.md",
    import: () => import("../content/24-see-dhumma.md"),
    metadata: {"publish":true,"filename":"24-see-dhumma.md","sortKey":["900000024","see","dhumma.md"],"slug":"see-dhumma","title":"มองทุกสิ่งเป็นธรรมชาติ น้อมรับสิ่งที่เกิด ในสภาวะจิต","titlePrev":"มองทุกสิ่งเป็นธรรมชาติ น้อมรับสิ่งที่เกิด ในสภาวะจิต","tags":["ข้อธรรม"]},
    paginate: {"prev":{"publish":true,"filename":"23-suicide.md","sortKey":["900000023","suicide.md"],"slug":"suicide","title":"กรรมจากการฆ่าตัวตาย","titlePrev":"กรรมจากการฆ่าตัวตาย","tags":["ข้อธรรม"],"bookPage":63},"next":{"publish":true,"filename":"25-stress.md","sortKey":["900000025","stress.md"],"slug":"stress","title":"สวดมนต์และนั่งสมาธิแล้วเครียด","titlePrev":"สวดมนต์และนั่งสมาธิแล้วมีแต่ความเครียด","tags":["ข้อธรรม"],"bookPage":69}},
  },
  {
    filename: "25-stress.md",
    import: () => import("../content/25-stress.md"),
    metadata: {"publish":true,"filename":"25-stress.md","sortKey":["900000025","stress.md"],"slug":"stress","title":"สวดมนต์และนั่งสมาธิแล้วเครียด","titlePrev":"สวดมนต์และนั่งสมาธิแล้วมีแต่ความเครียด","tags":["ข้อธรรม"],"bookPage":69},
    paginate: {"prev":{"publish":true,"filename":"24-see-dhumma.md","sortKey":["900000024","see","dhumma.md"],"slug":"see-dhumma","title":"มองทุกสิ่งเป็นธรรมชาติ น้อมรับสิ่งที่เกิด ในสภาวะจิต","titlePrev":"มองทุกสิ่งเป็นธรรมชาติ น้อมรับสิ่งที่เกิด ในสภาวะจิต","tags":["ข้อธรรม"]},"next":{"publish":true,"filename":"26-lightbulb.md","sortKey":["900000026","lightbulb.md"],"slug":"lightbulb","title":"หลอดไฟขุ่นมัวด้วยฝุ่นละออง","titlePrev":"การพิจารณา หลอดไฟแม้มีแสงสว่าง ให้มองเห็น แต่อาจขุ่นมัวได้ด้วยฝุ่นละออง","tags":["ข้อธรรม"]}},
  },
  {
    filename: "26-lightbulb.md",
    import: () => import("../content/26-lightbulb.md"),
    metadata: {"publish":true,"filename":"26-lightbulb.md","sortKey":["900000026","lightbulb.md"],"slug":"lightbulb","title":"หลอดไฟขุ่นมัวด้วยฝุ่นละออง","titlePrev":"การพิจารณา หลอดไฟแม้มีแสงสว่าง ให้มองเห็น แต่อาจขุ่นมัวได้ด้วยฝุ่นละออง","tags":["ข้อธรรม"]},
    paginate: {"prev":{"publish":true,"filename":"25-stress.md","sortKey":["900000025","stress.md"],"slug":"stress","title":"สวดมนต์และนั่งสมาธิแล้วเครียด","titlePrev":"สวดมนต์และนั่งสมาธิแล้วมีแต่ความเครียด","tags":["ข้อธรรม"],"bookPage":69},"next":{"publish":true,"filename":"27-present-and-past.md","sortKey":["900000027","present","and","past.md"],"slug":"present-and-past","title":"จิตบอกล่วงหน้าไม่ได้ แต่ดูปัจจุบันและย้อนหลังได้","titlePrev":"จิตบอกล่วงหน้าไม่ได้... แต่ดูปัจจุบันและย้อนหลังได้","tags":["ข้อธรรม"]}},
  },
  {
    filename: "27-present-and-past.md",
    import: () => import("../content/27-present-and-past.md"),
    metadata: {"publish":true,"filename":"27-present-and-past.md","sortKey":["900000027","present","and","past.md"],"slug":"present-and-past","title":"จิตบอกล่วงหน้าไม่ได้ แต่ดูปัจจุบันและย้อนหลังได้","titlePrev":"จิตบอกล่วงหน้าไม่ได้... แต่ดูปัจจุบันและย้อนหลังได้","tags":["ข้อธรรม"]},
    paginate: {"prev":{"publish":true,"filename":"26-lightbulb.md","sortKey":["900000026","lightbulb.md"],"slug":"lightbulb","title":"หลอดไฟขุ่นมัวด้วยฝุ่นละออง","titlePrev":"การพิจารณา หลอดไฟแม้มีแสงสว่าง ให้มองเห็น แต่อาจขุ่นมัวได้ด้วยฝุ่นละออง","tags":["ข้อธรรม"]},"next":{"publish":true,"filename":"28-soul.md","sortKey":["900000028","soul.md"],"slug":"soul","title":"วิญญาณนั้นคือผู้ที่ล่วงลับไปแล้ว","titlePrev":"วิญญาณนั้นคือผู้ที่ล่วงลับไปแล้ว","tags":["ข้อธรรม"],"bookPage":74}},
  },
  {
    filename: "28-soul.md",
    import: () => import("../content/28-soul.md"),
    metadata: {"publish":true,"filename":"28-soul.md","sortKey":["900000028","soul.md"],"slug":"soul","title":"วิญญาณนั้นคือผู้ที่ล่วงลับไปแล้ว","titlePrev":"วิญญาณนั้นคือผู้ที่ล่วงลับไปแล้ว","tags":["ข้อธรรม"],"bookPage":74},
    paginate: {"prev":{"publish":true,"filename":"27-present-and-past.md","sortKey":["900000027","present","and","past.md"],"slug":"present-and-past","title":"จิตบอกล่วงหน้าไม่ได้ แต่ดูปัจจุบันและย้อนหลังได้","titlePrev":"จิตบอกล่วงหน้าไม่ได้... แต่ดูปัจจุบันและย้อนหลังได้","tags":["ข้อธรรม"]},"next":{"publish":true,"filename":"29-fate.md","sortKey":["900000029","fate.md"],"slug":"fate","title":"การพิจารณา ศรัทธา","titlePrev":"การพิจารณา ศรัทธา","tags":["ข้อธรรม"]}},
  },
  {
    filename: "29-fate.md",
    import: () => import("../content/29-fate.md"),
    metadata: {"publish":true,"filename":"29-fate.md","sortKey":["900000029","fate.md"],"slug":"fate","title":"การพิจารณา ศรัทธา","titlePrev":"การพิจารณา ศรัทธา","tags":["ข้อธรรม"]},
    paginate: {"prev":{"publish":true,"filename":"28-soul.md","sortKey":["900000028","soul.md"],"slug":"soul","title":"วิญญาณนั้นคือผู้ที่ล่วงลับไปแล้ว","titlePrev":"วิญญาณนั้นคือผู้ที่ล่วงลับไปแล้ว","tags":["ข้อธรรม"],"bookPage":74},"next":{"publish":true,"filename":"30-charn4.md","sortKey":["900000030","charn4.md"],"slug":"charn4","title":"สมาธิในฌาน 4","titlePrev":"สมาธิในฌาน 4","tags":["ข้อธรรม"],"bookPage":81}},
  },
  {
    filename: "30-charn4.md",
    import: () => import("../content/30-charn4.md"),
    metadata: {"publish":true,"filename":"30-charn4.md","sortKey":["900000030","charn4.md"],"slug":"charn4","title":"สมาธิในฌาน 4","titlePrev":"สมาธิในฌาน 4","tags":["ข้อธรรม"],"bookPage":81},
    paginate: {"prev":{"publish":true,"filename":"29-fate.md","sortKey":["900000029","fate.md"],"slug":"fate","title":"การพิจารณา ศรัทธา","titlePrev":"การพิจารณา ศรัทธา","tags":["ข้อธรรม"]},"next":{"publish":true,"filename":"31-i-am-better.md","sortKey":["900000031","i","am","better.md"],"slug":"i-am-better","title":"คนอื่นดีไม่เท่าตัวเอง","titlePrev":"กรรมติเตียนคนอื่นว่าทำดีไม่ได้เท่าตัวเอง","tags":["ข้อธรรม"],"bookPage":85}},
  },
  {
    filename: "31-i-am-better.md",
    import: () => import("../content/31-i-am-better.md"),
    metadata: {"publish":true,"filename":"31-i-am-better.md","sortKey":["900000031","i","am","better.md"],"slug":"i-am-better","title":"คนอื่นดีไม่เท่าตัวเอง","titlePrev":"กรรมติเตียนคนอื่นว่าทำดีไม่ได้เท่าตัวเอง","tags":["ข้อธรรม"],"bookPage":85},
    paginate: {"prev":{"publish":true,"filename":"30-charn4.md","sortKey":["900000030","charn4.md"],"slug":"charn4","title":"สมาธิในฌาน 4","titlePrev":"สมาธิในฌาน 4","tags":["ข้อธรรม"],"bookPage":81},"next":{"publish":true,"filename":"32-gamaraka.md","sortKey":["900000032","gamaraka.md"],"slug":"gamaraka","title":"ชำระกามราคะ","titlePrev":"การพิจารณา การชำระกามราคะ","tags":["ข้อธรรม"]}},
  },
  {
    filename: "32-gamaraka.md",
    import: () => import("../content/32-gamaraka.md"),
    metadata: {"publish":true,"filename":"32-gamaraka.md","sortKey":["900000032","gamaraka.md"],"slug":"gamaraka","title":"ชำระกามราคะ","titlePrev":"การพิจารณา การชำระกามราคะ","tags":["ข้อธรรม"]},
    paginate: {"prev":{"publish":true,"filename":"31-i-am-better.md","sortKey":["900000031","i","am","better.md"],"slug":"i-am-better","title":"คนอื่นดีไม่เท่าตัวเอง","titlePrev":"กรรมติเตียนคนอื่นว่าทำดีไม่ได้เท่าตัวเอง","tags":["ข้อธรรม"],"bookPage":85},"next":{"publish":true,"filename":"33-mara.md","sortKey":["900000033","mara.md"],"slug":"mara","title":"มาร","titlePrev":"มาร","tags":["ข้อธรรม"],"bookPage":88}},
  },
  {
    filename: "33-mara.md",
    import: () => import("../content/33-mara.md"),
    metadata: {"publish":true,"filename":"33-mara.md","sortKey":["900000033","mara.md"],"slug":"mara","title":"มาร","titlePrev":"มาร","tags":["ข้อธรรม"],"bookPage":88},
    paginate: {"prev":{"publish":true,"filename":"32-gamaraka.md","sortKey":["900000032","gamaraka.md"],"slug":"gamaraka","title":"ชำระกามราคะ","titlePrev":"การพิจารณา การชำระกามราคะ","tags":["ข้อธรรม"]},"next":{"publish":true,"filename":"34-stillness-and-not-stillness.md","sortKey":["900000034","stillness","and","not","stillness.md"],"slug":"stillness-and-not-stillness","title":"ความเที่ยงและไม่เที่ยง","titlePrev":"ความเที่ยงและไม่เที่ยง","tags":["ข้อธรรม"],"bookPage":89}},
  },
  {
    filename: "34-stillness-and-not-stillness.md",
    import: () => import("../content/34-stillness-and-not-stillness.md"),
    metadata: {"publish":true,"filename":"34-stillness-and-not-stillness.md","sortKey":["900000034","stillness","and","not","stillness.md"],"slug":"stillness-and-not-stillness","title":"ความเที่ยงและไม่เที่ยง","titlePrev":"ความเที่ยงและไม่เที่ยง","tags":["ข้อธรรม"],"bookPage":89},
    paginate: {"prev":{"publish":true,"filename":"33-mara.md","sortKey":["900000033","mara.md"],"slug":"mara","title":"มาร","titlePrev":"มาร","tags":["ข้อธรรม"],"bookPage":88},"next":{"publish":true,"filename":"35-parent.md","sortKey":["900000035","parent.md"],"slug":"parent","title":"การดูแลพ่อแม่","titlePrev":"การดูแลพ่อแม่","tags":["ข้อธรรม"]}},
  },
  {
    filename: "35-parent.md",
    import: () => import("../content/35-parent.md"),
    metadata: {"publish":true,"filename":"35-parent.md","sortKey":["900000035","parent.md"],"slug":"parent","title":"การดูแลพ่อแม่","titlePrev":"การดูแลพ่อแม่","tags":["ข้อธรรม"]},
    paginate: {"prev":{"publish":true,"filename":"34-stillness-and-not-stillness.md","sortKey":["900000034","stillness","and","not","stillness.md"],"slug":"stillness-and-not-stillness","title":"ความเที่ยงและไม่เที่ยง","titlePrev":"ความเที่ยงและไม่เที่ยง","tags":["ข้อธรรม"],"bookPage":89},"next":{"publish":true,"filename":"36-feeling-is-soul-s-decorate.md","sortKey":["900000036","feeling","is","soul","s","decorate.md"],"slug":"feeling-is-soul-s-decorate","title":"อารมณ์ คือสิ่งปรุงแต่ง(ของจิต)","titlePrev":"อารมณ์ คือสิ่งปรุงแต่ง(ของจิต)","tags":["ข้อธรรม"]}},
  },
  {
    filename: "36-feeling-is-soul-s-decorate.md",
    import: () => import("../content/36-feeling-is-soul-s-decorate.md"),
    metadata: {"publish":true,"filename":"36-feeling-is-soul-s-decorate.md","sortKey":["900000036","feeling","is","soul","s","decorate.md"],"slug":"feeling-is-soul-s-decorate","title":"อารมณ์ คือสิ่งปรุงแต่ง(ของจิต)","titlePrev":"อารมณ์ คือสิ่งปรุงแต่ง(ของจิต)","tags":["ข้อธรรม"]},
    paginate: {"prev":{"publish":true,"filename":"35-parent.md","sortKey":["900000035","parent.md"],"slug":"parent","title":"การดูแลพ่อแม่","titlePrev":"การดูแลพ่อแม่","tags":["ข้อธรรม"]},"next":{"publish":true,"filename":"37-naka.md","sortKey":["900000037","naka.md"],"slug":"naka","title":"พญานาค","titlePrev":"พญานาค...เหมือนญาติผู้ใหญ่","tags":["ข้อธรรม"]}},
  },
  {
    filename: "37-naka.md",
    import: () => import("../content/37-naka.md"),
    metadata: {"publish":true,"filename":"37-naka.md","sortKey":["900000037","naka.md"],"slug":"naka","title":"พญานาค","titlePrev":"พญานาค...เหมือนญาติผู้ใหญ่","tags":["ข้อธรรม"]},
    paginate: {"prev":{"publish":true,"filename":"36-feeling-is-soul-s-decorate.md","sortKey":["900000036","feeling","is","soul","s","decorate.md"],"slug":"feeling-is-soul-s-decorate","title":"อารมณ์ คือสิ่งปรุงแต่ง(ของจิต)","titlePrev":"อารมณ์ คือสิ่งปรุงแต่ง(ของจิต)","tags":["ข้อธรรม"]},"next":{"publish":true,"filename":"38-light-of-dhumma.md","sortKey":["900000038","light","of","dhumma.md"],"slug":"light-of-dhumma","title":"แสงแห่งธรรม","titlePrev":"การเชื่อมจิต","tags":["สถานปฏิบัติธรรม"]}},
  },
  {
    filename: "38-light-of-dhumma.md",
    import: () => import("../content/38-light-of-dhumma.md"),
    metadata: {"publish":true,"filename":"38-light-of-dhumma.md","sortKey":["900000038","light","of","dhumma.md"],"slug":"light-of-dhumma","title":"แสงแห่งธรรม","titlePrev":"การเชื่อมจิต","tags":["สถานปฏิบัติธรรม"]},
    paginate: {"prev":{"publish":true,"filename":"37-naka.md","sortKey":["900000037","naka.md"],"slug":"naka","title":"พญานาค","titlePrev":"พญานาค...เหมือนญาติผู้ใหญ่","tags":["ข้อธรรม"]}},
  }  
]
